# Security Constraints
security:
  oauth2:
    resource:
        tokenInfoUri: ${OAUTH_TOKEN_URI:http://localhost:8080/oauth/check_token/}
        token-type: Bearer
    client:
      client-id: ${OAUTH_CLIENT_ID:example}
      client-secret: ${OAUTH_CLIENT_SECRET:my-pwd-test}